### ISSUE TITLE
The content_template module cannot delete template

### ISSUE THREAD

**Issue by trippsc2** [ansible-collections/vmware.vmware#90]
The content_template.py file on line 182 references the 'library' variable that was replaced with 'library_id' in commit f18dec4.

Testing seems to be missing for this module, as this should always fail.

**Comment by mikemorency** [comment]
Hi @trippsc2,

Thank you for opening this issue. Ive opened a PR to fix the mistake and add tests to cover this part of the module. It should be included in the release in a few days
